export const statesData={
    data:()=>{
        var dictionaryData={};
        dictionaryData["AL"]="Alabama";
        dictionaryData["AK"]="Alaska";
        dictionaryData["AZ"]="Arizona";
        dictionaryData["AR"]="Arkansas";
        dictionaryData["CA"]="California";
        dictionaryData["CO"]="Colorado";
        dictionaryData["CT"]="Connecticut";
        dictionaryData["DE"]="Delaware";
        dictionaryData["DC"]="District of Columbia";
        dictionaryData["FL"]="Florida";
        dictionaryData["GA"]="Georgia";
        dictionaryData["HI"]="Hawaii";
        dictionaryData["ID"]="Idaho";
        dictionaryData["IL"]="Illinois";
        dictionaryData["IN"]="Indiana";
        dictionaryData["IA"]="Iowa";
        dictionaryData["KS"]="Kansas";
        dictionaryData["KY"]="Kentucky";
        dictionaryData["LA"]="Louisiana";
        dictionaryData["ME"]="Maine";
        dictionaryData["MD"]="Maryland";
        dictionaryData["MA"]="Massachusetts";
        dictionaryData["MI"]="Michigan";
        dictionaryData["MN"]="Minnesota";
        dictionaryData["MS"]="Mississippi";
        dictionaryData["MO"]="Missouri";
        dictionaryData["MT"]="Montana";
        dictionaryData["NE"]="Nebraska";
        dictionaryData["NV"]="Nevada";
        dictionaryData["NH"]="New Hampshire";
        dictionaryData["NJ"]="New Jersey";
        dictionaryData["NM"]="New Mexico";
        dictionaryData["NY"]="New York";
        dictionaryData["NC"]="North Carolina";
        dictionaryData["ND"]="North Dakota";
        dictionaryData["OH"]="Ohio";
        dictionaryData["OK"]="Oklahoma";
        dictionaryData["OR"]="Oregon";
        dictionaryData["PA"]="Pennsylvania";
        dictionaryData["RI"]="Rhode Island";
        dictionaryData["SC"]="South Carolina";
        dictionaryData["SD"]="South Dakota";
        dictionaryData["TN"]="Tennessee";
        dictionaryData["TX"]="Texas";
        dictionaryData["UT"]="Utah";
        dictionaryData["VT"]="Vermont";
        dictionaryData["VA"]="Virginia";
        dictionaryData["WA"]="Washington";
        dictionaryData["WV"]="West Virginia";
        dictionaryData["WI"]="Wisconsin";
        dictionaryData["WY"]="Wyoming";


        return dictionaryData;
    }    
}
